dist: xenial
language: python
python:
  - '3.7'
install:
  - 'pip install pipenv'
  - 'cd app'
  - 'pipenv sync'
env:
  - DJANGO_SETTINGS_MODULE=feedreader.settings.test
script:
  - 'python manage.py test feedreader'
