language: python
python:
  - '3.7-dev'
install:
  - 'pip install pipenv'
  - 'cd app'
  - 'pipenv sync'
env:
  - DJANGO_SETTINGS_MODULE=feedreader.settings.test
script:
  - 'python app/manage.py test feedreader'