version: '3.7'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: unless-stopped

  redis:
    image: redis:5-alpine
    restart: unless-stopped

  web:
    build: ./app
    command: gunicorn feedreader.wsgi:application --bind 0.0.0.0:8000 -w 5
    env_file:
      - web-variables.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 127.0.0.1:1337:8000
    depends_on:
      - db
    restart: unless-stopped
    secrets:
      - secret_key

  celery:
    build: ./app
    command: celery -A feedreader worker -l info
    env_file:
      - web-variables.env
    depends_on:
      - redis
    restart: unless-stopped
    secrets:
      - secret_key

  beat:
    build: ./app
    command: celery -A feedreader beat -l info
    env_file:
      - web-variables.env
    depends_on:
      - redis
    restart: unless-stopped
    secrets:
      - secret_key

volumes:
  postgres_data:
  static_volume:
  media_volume:

secrets:
  secret_key:
    file: secret_key.txt
