version: '3.7'

services:
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:5-alpine

  web:
    build: ./app
    command: gunicorn feedreader.wsgi:application --bind 0.0.0.0:8000 -w 5
    env_file:
      - web-variables.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    secrets:
      - secret_key

  celery:
    build: ./app
    command: celery -A feedreader worker -l info
    env_file:
      - web-variables.env
    depends_on:
      - redis
    secrets:
      - secret_key

  beat:
    build: ./app
    command: celery -A feedreader beat -l info
    env_file:
      - web-variables.env
    depends_on:
      - redis
    secrets:
      - secret_key

volumes:
  postgres_data:
  static_volume:
  media_volume:

secrets:
  secret_key:
    file: secret_key.txt
