version: '3.7'

x-app: &default-app
  build: ./app
  env_file:
    - web-variables.env
  secrets:
    - secret_key

services:
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:5-alpine

  web:
    <<: *default-app
    command: gunicorn feedreader.wsgi:application --bind 0.0.0.0:8000 -w 5
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  celery:
    <<: *default-app
    command: celery -A feedreader worker -l info
    depends_on:
      - redis

  beat:
    <<: *default-app
    command: celery -A feedreader beat -l info
    depends_on:
      - redis

  ingress:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/usr/share/nginx/html/media:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:

secrets:
  secret_key:
    file: secret_key.txt
