version: "3.7"

services:
  db:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  web:
    restart: unless-stopped
    image: ghcr.io/jawsper/feedreader:latest
  celery:
    restart: unless-stopped
    image: ghcr.io/jawsper/feedreader:latest
  beat:
    restart: unless-stopped
    image: ghcr.io/jawsper/feedreader:latest
  ingress:
    restart: unless-stopped
    ports:
      - 127.0.0.1:1337:80
