# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 15:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedreader.models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedreader', '0007_outline_unread_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('sort_position', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sort_order_asc', models.BooleanField(default=True)),
                ('show_only_new', models.BooleanField(default=True)),
                ('folder_opened', models.BooleanField(default=True)),
                ('unread_count', models.IntegerField(db_index=True, default=0)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedreader.Feed')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feedreader.TreeOutline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, feedreader.models.DisplayTitleMixIn),
        ),
    ]
