# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedreader', '0008_treeoutline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='feedreader.Outline'),
        ),
    ]
