# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedreader', '0011_auto_20170316_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldoutline',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='oldoutline',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='oldoutline',
            name='user',
        ),
        migrations.DeleteModel(
            name='OldOutline',
        ),
    ]
