# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedreader', '0012_auto_20170316_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outline',
            name='sort_position',
        ),
    ]
