# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedreader.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigStore",
            fields=[
                (
                    "key",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("xmlUrl", models.CharField(max_length=1000)),
                ("htmlUrl", models.CharField(max_length=1000)),
                (
                    "faviconUrl",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("lastPubDate", models.DateTimeField(blank=True, null=True)),
                ("lastUpdated", models.DateTimeField(blank=True, null=True)),
                (
                    "lastStatus",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("disabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("link", models.CharField(max_length=1000)),
                ("category", models.CharField(blank=True, max_length=1000, null=True)),
                ("pubDate", models.DateTimeField()),
                ("guid", models.CharField(db_index=True, max_length=1000)),
                ("guid_is_permalink", models.BooleanField(default=False)),
                ("author", models.CharField(blank=True, max_length=1000, null=True)),
                ("content", models.TextField()),
                ("description", models.TextField()),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedreader.Feed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starred", models.BooleanField(default=False)),
                ("read", models.BooleanField(db_index=True, default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedreader.Post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                ("expire", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="userpost",
            unique_together=set([("user", "post")]),
        ),
        migrations.AlterUniqueTogether(
            name="configstore",
            unique_together=set([("key", "user")]),
        ),
        migrations.AlterField(
            model_name="post",
            name="guid",
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name="feed",
            name="lastETag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="quirkFixNotXml",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="feed",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name="Outline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("sort_order_asc", models.BooleanField(default=True)),
                ("show_only_new", models.BooleanField(default=True)),
                ("folder_opened", models.BooleanField(default=True)),
                ("unread_count", models.IntegerField(db_index=True, default=0)),
                ("lft", models.PositiveIntegerField(db_index=True, editable=False)),
                ("rght", models.PositiveIntegerField(db_index=True, editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(db_index=True, editable=False)),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedreader.Feed",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="feedreader.Outline",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, feedreader.models.DisplayTitleMixIn),
        ),
    ]
