# Generated by Django 4.1.3 on 2022-11-22 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedreader.models.display_title


class Migration(migrations.Migration):

    replaces = [
        ("feedreader", "0001_squashed_0014_auto_20171203_2154"),
        ("feedreader", "0002_add_inserted_date"),
        ("feedreader", "0003_set_inserted_date"),
        ("feedreader", "0004_remove_null_from_inserted_date"),
        ("feedreader", "0005_feed_quirk_fix_invalid_publication_date"),
        ("feedreader", "0006_mptt_update"),
        ("feedreader", "0007_feed_favicon"),
        ("feedreader", "0008_feed_quirk_fix_override_encoding"),
        ("feedreader", "0009_remove_feed_quirkfixnotxml"),
        ("feedreader", "0010_camel_to_snake_case"),
        ("feedreader", "0011_delete_usertoken"),
        ("feedreader", "0012_feed_is_nsfw"),
        ("feedreader", "0013_userconfig"),
        ("feedreader", "0014_delete_configstore"),
        ("feedreader", "0015_feed_errored_since"),
        ("feedreader", "0016_rename_outline_oldoutline"),
        ("feedreader", "0017_auto_20221122_1428"),
        ("feedreader", "0018_outline"),
        ("feedreader", "0019_copy_oldoutline_to_outline"),
        ("feedreader", "0020_delete_oldoutline"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("xml_url", models.CharField(max_length=1000)),
                ("html_url", models.CharField(max_length=1000)),
                (
                    "favicon_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("last_pub_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("disabled", models.BooleanField(default=False)),
                ("last_etag", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "quirk_fix_invalid_publication_date",
                    models.BooleanField(default=False),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="favicon"),
                ),
                (
                    "quirk_fix_override_encoding",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_nsfw", models.BooleanField(default=False)),
                (
                    "errored_since",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("link", models.CharField(max_length=1000)),
                ("category", models.CharField(blank=True, max_length=1000, null=True)),
                ("pubDate", models.DateTimeField()),
                ("guid", models.CharField(db_index=True, max_length=250)),
                ("guid_is_permalink", models.BooleanField(default=False)),
                ("author", models.CharField(blank=True, max_length=1000, null=True)),
                ("content", models.TextField()),
                ("description", models.TextField()),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedreader.feed",
                    ),
                ),
                ("inserted_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_only_unread", models.BooleanField(default=True)),
                ("show_nsfw_feeds", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("sort_order_asc", models.BooleanField(default=True)),
                ("show_only_new", models.BooleanField(default=True)),
                ("folder_opened", models.BooleanField(default=True)),
                ("unread_count", models.IntegerField(db_index=True, default=0)),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedreader.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_outlines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, feedreader.models.display_title.DisplayTitleMixIn),
        ),
        migrations.CreateModel(
            name="UserPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starred", models.BooleanField(default=False)),
                ("read", models.BooleanField(db_index=True, default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedreader.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "post")},
            },
        ),
    ]
