# Generated by Django 2.2.4 on 2019-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedreader', '0004_remove_null_from_inserted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='quirk_fix_invalid_publication_date',
            field=models.BooleanField(default=False),
        ),
    ]
