# Generated by Django 2.2.5 on 2019-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedreader", "0005_feed_quirk_fix_invalid_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outline",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="outline",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="outline",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
