# Generated by Django 2.2.6 on 2019-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedreader", "0006_mptt_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="favicon",
            field=models.ImageField(blank=True, null=True, upload_to="favicon"),
        ),
    ]
