# Generated by Django 2.2.9 on 2020-01-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedreader', '0007_feed_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='quirk_fix_override_encoding',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
