# Generated by Django 2.2.9 on 2020-01-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedreader', '0008_feed_quirk_fix_override_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='quirkFixNotXml',
        ),
    ]
