# Generated by Django 3.2.7 on 2021-10-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedreader", "0011_delete_usertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="is_nsfw",
            field=models.BooleanField(default=False),
        ),
    ]
