# Generated by Django 3.2.7 on 2021-10-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedreader", "0013_userconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfigStore",
        ),
    ]
