# Generated by Django 3.2.15 on 2022-10-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedreader', '0014_delete_configstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='errored_since',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
