# Generated by Django 3.2.16 on 2022-11-22 14:28

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("feedreader", "0016_rename_outline_oldoutline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oldoutline",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="feedreader.oldoutline",
            ),
        ),
        migrations.AlterField(
            model_name="oldoutline",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="oldoutline",
            name="unread_count",
            field=models.IntegerField(default=0),
        ),
    ]
