# Generated by Django 3.2.16 on 2022-11-21 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedreader.models.display_title


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedreader", "0017_auto_20221122_1428"),
    ]

    operations = [
        migrations.CreateModel(
            name="Outline",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(db_index=True, max_length=500)),
                ("sort_order_asc", models.BooleanField(default=True)),
                ("show_only_new", models.BooleanField(default=True)),
                ("folder_opened", models.BooleanField(default=True)),
                ("unread_count", models.IntegerField(db_index=True, default=0)),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedreader.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_outlines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, feedreader.models.display_title.DisplayTitleMixIn),
        ),
    ]
