# Generated by Django 3.2.16 on 2022-11-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedreader", "0019_copy_oldoutline_to_outline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OldOutline",
        ),
    ]
